name: dash_StockCorr #Environment name
dependencies:
  - python=3.8.10
  - pip
  - pip:
    - numpy==1.18.1
    - pandas==1.0.1
    - dash==2.0.0
    - gunicorn==20.0.4
    - plotly==5.6.0
    - yfinance==0.1.70
    - scipy==1.8.0
    - dash-bootstrap-components==1